# Generated by Django 4.0.1 on 2022-01-18 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0002_campaign_qa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mgr', to='qms_app.profile'),
        ),
    ]
