# Generated by Django 4.0.1 on 2022-01-18 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qms_app', '0004_alter_campaign_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='test',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='test', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
