# Generated by Django 4.0.1 on 2022-01-18 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qms_app', '0005_campaign_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='manager',
            new_name='manager_id',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='QA',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='test',
        ),
        migrations.AddField(
            model_name='campaign',
            name='qa_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='qa', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
