# Generated by Django 4.0.1 on 2022-01-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0008_rename_call_duration_hr_outbound_call_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbound',
            name='audit_duration',
            field=models.TimeField(default='00:00:00.0'),
            preserve_default=False,
        ),
    ]
