# Generated by Django 4.0.1 on 2022-01-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0009_outbound_audit_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.CharField(max_length=150)),
                ('campaign_type', models.CharField(default='Intbound', max_length=50)),
                ('emp_id', models.IntegerField()),
                ('associate_name', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=50)),
                ('concept', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_contact', models.CharField(max_length=15)),
                ('call_date', models.DateField()),
                ('call_duration', models.IntegerField(blank=True, null=True)),
                ('audit_date', models.DateField()),
                ('quality_analyst', models.CharField(max_length=100)),
                ('team_lead', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('am', models.CharField(max_length=100)),
                ('week', models.CharField(max_length=10)),
                ('ce_1', models.IntegerField()),
                ('ce_2', models.IntegerField()),
                ('ce_3', models.IntegerField()),
                ('ce_4', models.IntegerField()),
                ('ce_5', models.IntegerField()),
                ('ce_6', models.IntegerField()),
                ('business_1', models.IntegerField()),
                ('business_2', models.IntegerField()),
                ('compliance_1', models.IntegerField()),
                ('compliance_2', models.IntegerField()),
                ('compliance_3', models.IntegerField()),
                ('compliance_4', models.IntegerField()),
                ('compliance_5', models.IntegerField()),
                ('areas_improvement', models.TextField()),
                ('positives', models.TextField()),
                ('comments', models.TextField()),
                ('added_by', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('closed_date', models.DateTimeField(null=True)),
                ('emp_comments', models.TextField(null=True)),
                ('ce_total', models.IntegerField(null=True)),
                ('business_total', models.IntegerField(null=True)),
                ('compliance_total', models.IntegerField(null=True)),
                ('overall_score', models.IntegerField(null=True)),
                ('fatal', models.BooleanField(default=False)),
                ('fatal_count', models.IntegerField(default=0)),
                ('dispute_status', models.BooleanField(default=False)),
                ('audit_duration', models.TimeField()),
            ],
        ),
    ]
