# Generated by Django 4.0.1 on 2022-01-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0010_inbound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='campaign_type',
            field=models.CharField(default='Inbound', max_length=50),
        ),
    ]
