# Generated by Django 4.0.1 on 2022-01-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0011_alter_inbound_campaign_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbound',
            name='ce_10',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inbound',
            name='ce_11',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inbound',
            name='ce_7',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inbound',
            name='ce_8',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inbound',
            name='ce_9',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
