# Generated by Django 4.0.1 on 2022-01-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0012_inbound_ce_10_inbound_ce_11_inbound_ce_7_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='emp_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='emp_id',
            field=models.CharField(max_length=30),
        ),
    ]
