# Generated by Django 4.0.1 on 2022-01-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0015_digitalswissgold'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='page_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='digitalswissgold',
            name='page_type',
            field=models.CharField(default='Digital', max_length=50),
        ),
        migrations.AddField(
            model_name='emailchat',
            name='page_type',
            field=models.CharField(default='Email', max_length=50),
        ),
        migrations.AddField(
            model_name='inbound',
            name='page_type',
            field=models.CharField(default='Inbound', max_length=50),
        ),
        migrations.AddField(
            model_name='outbound',
            name='page_type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
    ]
