# Generated by Django 4.0.1 on 2022-02-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0021_noomeva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoomEva',
        ),
        migrations.DeleteModel(
            name='NoomPod',
        ),
    ]
